# SHARED PORT 80
server {
    listen 80;
    server_name farmxnap-api.duckdns.org farmxnap-staging-api.duckdns.org;

    # For CertBot renewals
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all http to https
    location / {
        return 301 https://$host$request_uri;
    }
}

# PRODUCTION
server {
    listen 443 ssl;
    server_name farmxnap-api.duckdns.org;

    # Point to the certificates
    ssl_certificate /etc/letsencrypt/live/farmxnap-api.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/farmxnap-api.duckdns.org/privkey.pem;

   include params/ssl_params;

    location / {
        proxy_pass http://app:3333;
        
        include params/proxy_params;
    }
}

# STAGING
server {
    listen 443 ssl;
    server_name farmxnap-staging-api.duckdns.org;

    # Point to the certificates
    ssl_certificate /etc/letsencrypt/live/farmxnap-staging-api.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/farmxnap-staging-api.duckdns.org/privkey.pem;

   include params/ssl_params;

    location / {
        proxy_pass http://app-staging:3333;
        
        include params/proxy_params;
    }
}