name: Remote Update and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: ${{secrets.REMOTE_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd ~/FarmXnap-Backend
            git pull origin main
            docker compose up --build -d
            docker compose exec -T app node build/ace migration:run --force
            docker system prune -f
